name: ABuild and Release

on:
  push:
    branches: [ main ]  # or your default branch
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Adjust based on your project needs
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleMinApi26Debug

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/minApi26/debug
        if-no-files-found: error

    - name: Upload Build Outputs
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          app/build/outputs/apk/minApi26/debug
          !app/build/outputs/logs/
        if-no-files-found: error
