name: Android Checkout

on:
  workflow_dispatch:

jobs:
  checkout:
    name: update project if full commits
    runs-on: ubuntu-latest
    with:
      - uses: actions/checkout@v3
        fetch-depth: '1'
      - run: git checkout HEAD^
