name: Clear Gradle Build Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  clear_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Gradle Build Cache
        run: ./gradlew cleanBuildCache
