name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of commits
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s (%h)" > CHANGELOG.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: app/build/outputs/

      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.TAG_NAME }}
          release_name: Release v${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.txt
          artifacts: |
            app/build/outputs/apk-minApi26-debug.apk
